AWSTemplateFormatVersion: '2010-09-09'
Description: Create IAM Role

Resources:

  MyIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: MyExampleRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: Devops-Policy-demo
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetObject
                  - ec2:Describe*
                  - s3:PutObject
                  - s3:*
                Resource: "*"
